---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ngram)
library(stringdist)
library(spotifyr)
library(tidyverse)
library(httr)
library(jsonlite)
library(xml2)
library(ggplot2)
library(stringr)
library(tm)
library(wordcloud)
library(udpipe)
library(sna)
library(plotly)
library(moments)

Sys.setenv(SPOTIFY_CLIENT_ID = 'eeec0cd1dc4b4d40b22ebc424837390b')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '918a941879ba4a539d0de507b7e77764')

access_token <- get_spotify_access_token()
```

```{r}
chord_database <- data.frame(chord.name = c("C", "D", "E", "F", "G", "A", "B"),
                     chord.position = c(1, 3, 5, 6, 8, 10, 12))

# Funkcja zwraca listę zawierającą listy akordów piosenek odpowiadającm
# podnemu tytułowi i autorowi

search_chords <- function(title, author) {
  headers <- c(`Guitarparty-Api-Key` = "8b029c4b81a67c490ec89a1a50e7ba6bf720e909")
  res <- httr::GET(url = "http://api.guitarparty.com/v2/songs/", query = list(query = title), add_headers(headers))
  content_char <- rawToChar(res$content)
  content_JSON <- fromJSON(content_char)
  if (content_JSON$objects_count == 0) {
    return(NA)
  }else {
    songs <- content_JSON$objects
    chords_final <- list()
    for (j in 1:dim(songs)[1]) {
      if (grepl(author, songs[j, 'authors']) == TRUE) {
        chords_body <- songs[j,"body_chords_html"]
        Chords_html <- read_html(chords_body)
        chords_nodes <- as_list(xml_find_all(Chords_html, "//strong"))
        chords <- lapply(chords_nodes, function(x) x[[2]])
        chords_final <- append(chords_final, list(chords))
      }else {
        if (j == dim(songs)[1] && length(chords_final) == 0){
          return(NA)
        }else {
          next()
        }
      }
    }
    return(chords_final)
  }
}

# funkcja pobiera cechy audio wszystkich piosenek z wszystkich albumów danego artysty
# wydanych w podanym przedziale czasu razem z akordami

get_me_data <- function(artist, year1, year2){
  artist_tracks <- get_artist_audio_features(artist)
  base_data <- artist_tracks %>% filter(between(album_release_year, year1, year2)) %>% select(artist_id, artist_name, album_id,
              album_name, album_type, album_release_date, album_release_year, album_release_date_precision, track_id, 
              track_name, disc_number, track_number, available_markets, is_local,   duration_ms, danceability, energy,loudness,
              speechiness,  acousticness, instrumentalness, liveness, valence, tempo, key, mode, key_name, mode_name, key_mode)
  
  chords_modul <- data.frame(chords = NULL)
  for (i in 1:nrow(base_data)) {
    track_chords <- search_chords(base_data$track_name[i], base_data$artist_name[i])
    chords_modul[i, "chords"] <- list(track_chords)
  }
  
  final_data <- cbind(base_data, chords_modul)
  return(final_data)
}

add_chord_progression <- function(x){
  x_final <- x %>% mutate(chord.progression = NA, chord.mode = NA)
  x_final$chord.progression[1] <- 0
  for (m in 2:nrow(x_final)) {
    if (is.na(x_final$chord.pos[m])) {
      x_final$chord.progression[m] <- "pause"
      next()
    }else {
      if (x_final$chord.pos[1] <= x_final$chord.pos[m]) {
        x_final$chord.progression[m] <- x_final$chord.pos[m] - x_final$chord.pos[1]
        next()
      }else if (x_final$chord.pos[1] >x_final$chord.pos[m]) {
        x_final$chord.progression[m] <- 12 - x_final$chord.pos[1] + x_final$chord.pos[m]
        next()
      }
    }
  }
  for (m in 1:nrow(x_final)) {
    if (is.na(x_final$chord.pos[m])) {
      x_final$chord.progression[m] <- "pause"
      next()
    }else {
      if (grepl("m", x_final$chord.name[m]) && !grepl("maj", x_final$chord.name[m])) {
        x_final$chord.mode[m] <- 0
        next()
      }else {
        x_final$chord.mode[m] <- 1
        next()
      }
    }
  }
  
  return(x_final)
}

# funkcja na dodaje do każdej piosenki tabelkę z akordami i ich pozycjami na pięciolinii

add_chords_data <- function(data) {
  data_final <- data %>% mutate(chords_positions = NA)
  for (k in 1:nrow(data_final)) {
    if (!is.na(data_final$chords[k])) {
      chords_df <- t(as.data.frame(data_final$chords[k][[1]], col.names = 1:length(data_final$chords[k][[1]])))
      colnames(chords_df) <- "chord.name"
      chords_df <- as.data.frame(chords_df) %>% mutate(chord.pos = NA)
      for (l in 1:length(data_final$chords[k][[1]])) {
        if (substr(data_final$chords[k][[1]][[l]], 2, 2) == "#") {
          chords_df[l, "chord.pos"] <- chord_database %>% filter(chord.name == substr(data_final$chords[k][[1]][[l]], 1, 1)) %>%                                         select(chord.position) +1
          next()
        }else if (grepl("b", data_final$chords[k][[1]][[l]])) {
          chords_df[l, "chord.pos"] <- chord_database %>% filter(chord.name == substr(data_final$chords[k][[1]][[l]], 1, 1)) %>%                                         select(chord.position) -1
          next()
        }else if (grepl("hold", data_final$chords[k][[1]][[l]]) || grepl("pause", data_final$chords[k][[1]][[l]])) {
          chords_df[l, "chord.pos"] <- NA
          next()
        }else {
          chords_df[l, "chord.pos"] <- chord_database %>% filter(chord.name == substr(data_final$chords[k][[1]][[l]], 1, 1)) %>%                                         select(chord.position)
          next()
        }
      }
      chords_df <- add_chord_progression(chords_df)
      chords_df <- chords_df[,-2]
      data_final[k, "chords_positions"] <- list(list(chords_df))
      next()
    }else {
      data_final[k, "chords_positions"] <- NA
      next()
    }
  }
  return(data_final)
}

# Funkcja usuwa ze zbioru albumy o tej samej nazwie a innych ID zostawiając
# tylko jeden, z największą liczbą rynków na ktorych został wydany

remove_repetitive_albums <- function(your_data){
  remove_ids <- vector(mode = "character")
  l <- length(your_data$available_markets[[1]])
  change_pos <- 1
  for(n in 1:(nrow(your_data)-1)) {
    if (your_data$album_name[n] == your_data$album_name[n+1]) {
      if (your_data$album_id[n] != your_data$album_id[n+1]) {
        if (l >= length(your_data$available_markets[[n+1]])) {
          remove_ids <- append(remove_ids, your_data$album_id[n+1])
          next()
        }else {
          remove_ids <- append(remove_ids, your_data$album_id[change_pos])
          change_pos <- n+1
          l <- length(your_data$available_markets[[change_pos]])
          next()
        }
      }else{
        next()
      }
    }else {
      change_pos <- n+1
      l <- length(your_data$available_markets[[change_pos]])
      next()
    }
  }
  your_data_final <- your_data[!your_data$album_id %in% remove_ids,]
  row.names(your_data_final) <- 1:nrow(your_data_final)
  return(your_data_final)
}

remove_repetitive_tracks <- function(your_data){
  positive_checks <- your_data[1,]
  for(n in 2:(nrow(your_data))) {
    if (your_data$track_name[n] %in% positive_checks$track_name) {
      song_to_check <- your_data$track_name[n]
      if (your_data$artist_name[n] %in% positive_checks[positive_checks[,"track_name"] == song_to_check,"artist_name"]) {
        next()
      }else{
        positive_checks <- rbind(positive_checks, your_data[n,])
        next()
      }
    }else {
      positive_checks <- rbind(positive_checks, your_data[n,])
      next()
    }
  }
  return(positive_checks)
}

add_lyrics <- function(x) {
  artist_album <- x %>% distinct(artist_name, album_name, album_id)
  every_lyrics <- data.frame(album_name = NULL, lyrics = NULL)
  album_lyrics <- data.frame(album_name = NULL, lyrics = NULL)
  for(i in 1:nrow(artist_album)) {
    tryCatch({data_lyrics <- get_album_data(artist_album$artist_name[i], artist_album$album_name[i])
              album_lyrics <- data_lyrics %>% filter(album_id == artist_album$album_id[i]) %>% select(album_name, lyrics)}, error = function(e) {
                print(e)
              })
    if (i == 1) {
      if (nrow(album_lyrics) == 0) {
        l <- x %>% filter(album_id == artist_album$album_id[i]) %>% nrow()
        album_lyrics_puste <- data.frame(album_name = rep(NA, l), lyrics = rep(NA, l))
        every_lyrics <- rbind(every_lyrics, album_lyrics_puste)
        next()
      }else{
        every_lyrics <- rbind(every_lyrics, album_lyrics)
        next()
      }
    }else {
      if (album_lyrics$album_name[1] %in% artist_album$album_name[1:(i-1)]) {
        l <- x %>% filter(album_id == artist_album$album_id[i]) %>% nrow()
        album_lyrics_puste <- data.frame(album_name = rep(NA, l),lyrics = rep(NA, l))
        every_lyrics <- rbind(every_lyrics, album_lyrics_puste)
        next()
      }else {
        every_lyrics <- rbind(every_lyrics, album_lyrics)
        next()
      }
    }
  }
  x <- cbind(x, every_lyrics$lyrics)
  return(x)
}

take_highest_count <- function(x) {
  x_prep <- paste0(x,collapse =  " ")
  gram4and3 <- ngram_asweka(str = x_prep, min = 3, max = 8)
  progs8 <- vector(mode = "character")
  progs7 <- vector(mode = "character")
  progs6 <- vector(mode = "character")
  progs5 <- vector(mode = "character")
  progs4 <- vector(mode = "character")
  progs3 <- vector(mode = "character")

  for (i in seq(1, length(x)-7, 8)){
    progs8 <- append(progs8, gram4and3[i])
  }
  zmiana <- length(x)-7
  for (i in seq(zmiana+1, zmiana+length(x)-6, 7)){
    progs7 <- append(progs7, gram4and3[i])
  }
  zmiana <- zmiana+length(x)-6
  for (i in seq(zmiana+1, zmiana+length(x)-5, 6)){
    progs6 <- append(progs6, gram4and3[i])
  }
  zmiana <- zmiana+length(x)-5
  for (i in seq(zmiana+1, zmiana+length(x)-4, 5)){
    progs5 <- append(progs5, gram4and3[i])
  }
  zmiana <- zmiana+length(x)-4
  for (i in seq(zmiana+1, zmiana+length(x)-3, 4)){
    progs4 <- append(progs4, gram4and3[i])
  }
  zmiana <- zmiana+length(x)-3
  for (i in seq(zmiana+1, length(gram4and3), 3)){
    progs3 <- append(progs3, gram4and3[i])
  }
  progs4and3 <- data.frame(grupy = c(progs8, progs7, progs6, progs5, progs4, progs3),
                           len = c(rep(length(x)/8, length(progs8)), rep(length(x)/7, length(progs7)),
                                   rep(length(x)/6, length(progs6)),rep(length(x)/5, length(progs5)),
                                   rep(length(x)/4, length(progs4)), rep(length(x)/3, length(progs3))))
  
  progs_count <- progs4and3 %>% count(len, grupy)  %>% mutate(freq = n/len) %>% arrange(desc(freq))
  progs_best <- head(progs_count, n = 10)
  return(progs_best)
}

get_dists_chords <- function(dane, metoda){
  new_matrix<-matrix(nrow = length(dane), ncol = length(dane))
  for (n in 1:length(dane)){
    progression_sep_1 <- do.call("paste", c(dane$chords_positions[[n]][,c(2,3)], sep = ""))
    progression_tghr_1 <- paste0(progression_sep_1,collapse =  " ")
    for(m in 1:length(dane)) {
      progression_sep_2 <- do.call("paste", c(dane$chords_positions[[m]][,c(2,3)], sep = ""))
      progression_tghr_2 <- paste0(progression_sep_2,collapse =  " ")
      dist <- stringdist(progression_tghr_1, progression_tghr_2,method = metoda)
      new_matrix[n, m] <- dist
    }
  }
  return(new_matrix)
}

get_dists_lyrics <- function(dane, metoda){
  new_matrix<-matrix(nrow = length(dane), ncol = length(dane))
  for (n in 1:length(dane)){
    compare1 <- all_words[n,1]
    for(m in 1:length(dane)) {
      compare2 <- all_words[m,1]
      dist <- stringdist(compare1, compare2,method = metoda)
      new_matrix[n, m] <- dist
    }
  }
  return(new_matrix)
}

get_all_words <- function(dane) {
  new_df <- data.frame(lemma = NULL)
  for(n in 1:length(dane)){
    parsing <- udpipe(dane[[n]], "english")
    filtered_only <- parsing %>% select(lemma, upos) %>% filter(upos %in% c("NOUN", "ADV", "VERBE"))
    lemmas <- unlist(filtered_only$lemma)
    lemmas_one <- paste0(lemmas, collapse = " ")
    new_df[n, "lemma"] <- lemmas_one
  }
  return(new_df)
}

get_speech_part <- function(dane, speech_part) {
  new_df <- data.frame(lemma = NULL)
  for(n in 1:length(dane)){
    parsing <- udpipe(dane[[n]], "english")
    filtered_only <- parsing %>% select(lemma, upos) %>% filter(upos == speech_part)
    lemmas <- unlist(filtered_only$lemma)
    lemmas_one <- paste0(lemmas, collapse = " ")
    new_df[n, "lemma"] <- lemmas_one
  }
  return(new_df)
}
```

```{r}
# artists_1 <- c("Sam Smith", "Vance Joy", "Sia", "Aloe Blacc")
# artists_2 <- c("Ed Sheeran", "Katy Perry",  "Adele", "Lana Del Rey")
# artists_3 <- c("Bruno Mars", "Kelly Clarkson", "Alicia Keys", "Linkin Park")
# artists_4 <- c("Coldplay", "Rihanna", "Lil Wayne", "P!nk")
# artists_5 <- c("Justin Timberlake", "Chris Brown", "Fergie", "Christina Aguilera")
# tracks <- data.frame()
# for (m in 1:4) {
#   tracks <- rbind(tracks, get_me_data(artists_1[m], 2006, 2015)) }
# tracks <- rbind(tracks, get_me_data("Christina Aguilera", 2006, 2015))

tracks <- readRDS(file = "Lic_dane")
tracks_imp <- remove_repetitive_albums(tracks)

albums_to_remove <- c("A Head Full of Dreams Tour Edition", "A Thousand Suns Live Around the World", "Dream Your Life Away (Commentary)", "Funhouse Deluxe Version", "FutureSex/LoveSounds Deluxe Edition", "Ghost Stories Live 2014", "Good Girl Gone Bad: Reloaded", "Good Girl Gone Bad: The Remixes", "Katy Perry - Teenage Dream: The Complete Confection","Live at the Bedford", "Live from Sydney", "LIVING THINGS: Acapellas and Instrumentals", "Meteora Live Around the World", "Minutes to Midnight Live Around the World", "Nissan Live Sets At Yahoo! Music", "Rated R: Remixed", "Spotify Sessions", "Talk That Talk (Edited)", "Talk That Talk (Explicit)", "Teenage Dream: The Complete Confection", "The Dutchess Deluxe", "The Hunting Party: Acapellas + Instrumentals", "Ultraviolence - Audio Commentary", "Heartbeat Song (The Remixes)")
tracks_final <- tracks_imp[!(tracks_imp$album_name %in% albums_to_remove),]
tracks_final <- remove_repetitive_tracks(tracks_final)

remix <- grepl("Remix", tracks_final$track_name)
tracks_final <- tracks_final[!remix, ]
edit <- grepl("Edit", tracks_final$track_name)
tracks_final <- tracks_final[!edit, ]
Live <- grepl("Live", tracks_final$track_name)
tracks_final <- tracks_final[!Live, ]
remastered <- grepl("Remastered", tracks_final$track_name)
tracks_final <- tracks_final[!remastered, ]
comments <- grepl("Commentary", tracks_final$track_name)
tracks_final <- tracks_final[!comments, ]
row.names(tracks_final) <- 1:nrow(tracks_final)


# Ręczne obsłużenie wyjątku(jednym z akordów był "(f#m)")
tracks_final$chords[[323]][88] <- "F#m"
tracks_and_lyrics <- add_lyrics(tracks_final)
full_data <- add_chords_data(tracks_and_lyrics)
```

```{r}
# statystyki opisowe
full_data %>% distinct(artist_name) %>% count()
full_data %>% distinct(album_name) %>% count()
full_data %>% distinct(track_name) %>% count()
full_data %>% count(artist_name, track_name)

bar_data <- full_data %>% distinct(artist_name, album_name) %>% count(artist_name)
album_frequency <- ggplot(bar_data,aes(x= reorder(artist_name,n), n, fill = artist_name))+geom_bar(stat ="identity", show.legend = F) + coord_flip() + labs(title = "Liczba wydanych albumów w latach 2006 - 2015") + xlab("Artyści") + ylab("liczba albumów")
album_frequency
bar_song <- full_data %>% count(artist_name)
song_freq <- ggplot(bar_data,aes(x= reorder(artist_name,n), n, fill = artist_name))+geom_bar(stat ="identity", show.legend = F) + coord_flip() + labs(title = "Liczba wydanych piosenek w latach 2006 - 2015") + xlab("Artyści") + ylab("liczba piosenek")
song_freq

full_data$loudness <- -full_clear$loudness
descriptive_stats <- function(variable){
  opisowe <-  full_data %>% summarise(srednia= mean(variable), mediana = median(variable),
                                   var = var(variable), odchylenie_st = sd(variable),
                                   min = min(variable), max = max(variable),
                                   Q1 = quantile(variable, 0.25), Q3 = quantile(variable, 0.75),
                                   skosnosc = skewness(variable), kurtuoza = kurtosis(variable))
  return(opisowe)
}


ks.test(duration_s_impr$duration_s_impr)
shapiro.test(duration_s_impr$duration_s_impr)

x <- full_data$instrumentalness
qnt <- quantile(x, probs=c(0.25, 0.75), na.rm = T)
caps <- quantile(x, probs=c(0.05,0.95), na.rm = T)
H <- 1.5 * IQR(x, na.rm = T)
x[x < (qnt[1] - H)] <- caps[1]
x[x > (qnt[2] + H)] <- caps[2]


full_clear <- full_data$tempo[!full_data$tempo %in% boxplot.stats(full_data$tempo)$out]

full_data %>% group_by(album_release_year) %>% summarise(mediana = median(danceability)) %>% filter(album_release_year %in% c(2006, 2015))
full_data %>% filter(speechiness >=0.4) %>% select(artist_name, album_name, track_name)
full_data <- readRDS('Lic_dane_pelne')
comments <- grepl("Commentary", full_data$track_name)
full_data <- full_data[!comments, ]
saveRDS(full_data, file = "Lic_dane_pelne")

full_clear <- as.data.frame(full_clear)
plot(density(full_data$energy), main = "Gęstość Energiczności", xlab = "Energiczność", ylab = "Gęstość prawdopodobieństwa")
polygon(density(full_data$energy), col = "orange")

boxplot(full_data$instrumentalness, col = "orange", outline = T, horizontal = T, main = "Boxplot instrumentalness", xlab = "Instrumentalnes")

plot(ecdf(full_data$instrumentalness), main ="dytrybuanta intstrumentalness", xlab = "Instrumentalness", ylab = "prawdopodobieństwo P(X<x)")

ggplot(full_data) + geom_boxplot(aes(artist_name, speechiness), fill = "orange") + coord_flip() + labs(title = "Boxplot udziału mowy w piosenkach z podziałem na artystów") +  xlab("Artysta") + ylab("Udział mowy")


hist_gathered <- full_data %>%
  mutate(duration=duration_ms/60000) %>%
  select(artist_name, duration, danceability:valence) %>%
  tidyr::gather(feature, value, -artist_name)

ggplot(hist_gathered, aes(x=value)) + 
  geom_histogram() + 
  facet_wrap(~feature, scales = "free") +
  xlab("Wartość cechy") + 
  ylab("Liczebność") +
  theme_light() +
  ggsave("03_histogramy.png", width = 6, height = 4)

descriptive_stats(full_data$speechiness)
```

```{r}
# Analiza akordow
full_data <- readRDS("Lic_dane_pelne")
d_chords <- full_data %>%
  filter(!is.na(chords)) %>%
  count(artist_name) %>%
  filter(n > 1)
full_chords <- full_data %>% filter(artist_name %in% d_chords$artist_name) %>% filter(!is.na(chords))

most_used_progs <- data.frame(grupy = NULL, n = NULL)
for (n in 1:nrow(full_chords)) {
  progression_codes <- do.call("paste", c(full_chords$chords_positions[[n]][,c(2,3)], sep = ""))
  
  most_used_progs <- rbind(most_used_progs, take_highest_count(progression_codes))
}

total_count <- most_used_progs %>% count(grupy) %>% arrange(desc(n))


ggplot(head(total_count, n = 15), aes(x = reorder(grupy, n), y = n, fill = grupy)) + geom_col(show.legend = F) + coord_flip() + 
  labs(title="Liczba piosenek wykorzystujących daną progresję") + xlab("Progresje") + ylab("liczba piosenek")

dists_chord <- get_dists_chords(full_chords, "cosine")
plot.sociomatrix(dists_chord,drawlab = F)
max(song_dist)
dists_v <- vector(mode = "double")
for (i in 1:50) {
  for (j in (i+1):51) {
    dists_v <- append(dists_v, dists_chord[i, j])
  }
}

```
```{r}
# Analiza tekstów
lyrics_na <- full_data %>%
  filter(!is.na(lyrics))

not_null_rows <- !map_lgl(lyrics_na$lyrics, is.null)

lyrics_complete <- lyrics_na[not_null_rows,]

lyrics_char <- map(lyrics_complete$lyrics, ~.x$lyric)

lyrics_collapse <- map_chr(lyrics_char, paste, collapse = " ")

lyrics_complete <- lyrics_complete %>%
  mutate(lyric = lyrics_collapse) %>%
  filter(lyric != "NA")

lyrics_complete$modtext <- str_replace_all(lyrics_complete$lyric,"   "," ")
only_lyrics <- lyrics_complete$modtext

get_speech_part(only_lyrics, "ADV")
get_speech_part(only_lyrics, "NOUN")
get_speech_part(only_lyrics, "VERB")
ADVs <- ADVs$lemma
NOUNs <- NOUNs$lemma
VERBS <- VERBS$lemma
VERBS_corp<- Corpus(VectorSource(VERBS))
VERBS_corp<- tm_map(VERBS_corp, tolower)
VERBS_corp<- tm_map(VERBS_corp, removePunctuation)
VERBS_corp<- tm_map(VERBS_corp, removeWords, stopwords('english'))
lyricsTDM<-TermDocumentMatrix(VERBS_corp)
tdMatrix <- as.matrix(lyricsTDM)
sortedMatrix<-sort(rowSums(tdMatrix),decreasing=TRUE)
cloudFrame<-data.frame( word=names(sortedMatrix),freq=sortedMatrix)
wordcloud(cloudFrame$word,cloudFrame$freq,colors = c("darkred", "darkgreen", "black", "orange", "blue", "gold", "violet"), 
          max.words = 100)

all_words <- get_all_words(only_lyrics)

all_word_artist <- cbind(all_words, lyrics_complete$artist_name, lyrics_complete$album_release_year)
names(all_word_artist) <- c("lemma", "artist", "year")
words_1 <- all_word_artist %>% arrange(year)
song_dist <- get_dists_lyrics(words_1$lemma, "cosine")

plot_ly(
  x = words_1$artist, y = words_1$artist,
  z = song_dist, type = "heatmap"
)

```

```{r}
###############_____PIASKOWNICA_____##############################
# grepl("Rag'n'Bone Man", songs[12, 'authors'])
# 
# Know. <- get_album("7dwIWyB2jdJgL3P2JEgRKm")
# Know.data <- get_album_data("Jason Mraz", "YES!")
# K_tracks <- get_album_tracks("7dwIWyB2jdJgL3P2JEgRKm")
# JM <- get_artist("4phGZZrJZRo4ElhRtViYdl")
# JM_f <- get_artist_audio_features("Jason Mraz")
# JM_albums <- get_artist_albums("4phGZZrJZRo4ElhRtViYdl")
# some <- get_track_audio_features("33PdpAvnOMhA5HooKuFgbo")
# tracks %>% distinct(album_id, album_name) %>% count(album_name)
# saveRDS(tracks, file = "Lic_dane")
# saveRDS(full_data, file = "Lic_dane_pelne")
# table(unlist(data_chords$chords))

full_data %>% distinct(artist_name, track_name)

```